=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'cgi'

module DatadogAPIClient::V2
  class ConfluentCloudAccountsAPIAPI
    attr_accessor :api_client

    def initialize(api_client = DatadogAPIClient::APIClient.default)
      @api_client = api_client
    end

    # List Confluent accounts.
    #
    # @see #confluent_cloud_public1_with_http_info
    def confluent_cloud_public1(opts = {})
      data, _status_code, _headers = confluent_cloud_public1_with_http_info(opts)
      data
    end

    # List Confluent accounts.
    #
    # Get a Confluent account with the provided account id.
    #
    # @param opts [Hash] the optional parameters
    # @return [Array<(AccountConfigsResponse, Integer, Hash)>] AccountConfigsResponse data, response status code and response headers
    def confluent_cloud_public1_with_http_info(opts = {})

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ConfluentCloudAccountsAPIAPI.confluent_cloud_public1 ...'
      end
      # resource path
      local_var_path = '/api/v2/integrations/confluent-cloud/accounts'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'AccountConfigsResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth]

      new_options = opts.merge(
        :operation => :confluent_cloud_public1,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Get, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ConfluentCloudAccountsAPIAPI#confluent_cloud_public1\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Delete resource from Confluent account.
    #
    # @see #confluent_cloud_public10_with_http_info
    def confluent_cloud_public10(account_id, resource_id, opts = {})
      confluent_cloud_public10_with_http_info(account_id, resource_id, opts)
      nil
    end

    # Delete resource from Confluent account.
    #
    # Delete a Confluent resource with the provided resource id for the account associated with the provided account ID.
    #
    # @param account_id [String] None
    # @param resource_id [String] None
    # @param opts [Hash] the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def confluent_cloud_public10_with_http_info(account_id, resource_id, opts = {})

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ConfluentCloudAccountsAPIAPI.confluent_cloud_public10 ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling ConfluentCloudAccountsAPIAPI.confluent_cloud_public10"
      end
      # verify the required parameter 'resource_id' is set
      if @api_client.config.client_side_validation && resource_id.nil?
        fail ArgumentError, "Missing the required parameter 'resource_id' when calling ConfluentCloudAccountsAPIAPI.confluent_cloud_public10"
      end
      # resource path
      local_var_path = '/api/v2/integrations/confluent-cloud/accounts/{account_id}/resources/{resource_id}'.sub('{account_id}', CGI.escape(account_id.to_s).gsub('%2F', '/')).sub('{resource_id}', CGI.escape(resource_id.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth]

      new_options = opts.merge(
        :operation => :confluent_cloud_public10,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Delete, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ConfluentCloudAccountsAPIAPI#confluent_cloud_public10\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get Confluent account.
    #
    # @see #confluent_cloud_public2_with_http_info
    def confluent_cloud_public2(account_id, opts = {})
      data, _status_code, _headers = confluent_cloud_public2_with_http_info(account_id, opts)
      data
    end

    # Get Confluent account.
    #
    # Get the Confluent account with the provided account ID.
    #
    # @param account_id [String] None
    # @param opts [Hash] the optional parameters
    # @return [Array<(AccountConfigResponse, Integer, Hash)>] AccountConfigResponse data, response status code and response headers
    def confluent_cloud_public2_with_http_info(account_id, opts = {})

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ConfluentCloudAccountsAPIAPI.confluent_cloud_public2 ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling ConfluentCloudAccountsAPIAPI.confluent_cloud_public2"
      end
      # resource path
      local_var_path = '/api/v2/integrations/confluent-cloud/accounts/{account_id}'.sub('{account_id}', CGI.escape(account_id.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'AccountConfigResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth]

      new_options = opts.merge(
        :operation => :confluent_cloud_public2,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Get, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ConfluentCloudAccountsAPIAPI#confluent_cloud_public2\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Add Confluent account.
    #
    # @see #confluent_cloud_public3_with_http_info
    def confluent_cloud_public3(body, opts = {})
      data, _status_code, _headers = confluent_cloud_public3_with_http_info(body, opts)
      data
    end

    # Add Confluent account.
    #
    # Create a Confluent account.
    #
    # @param body [AddAccountRequest] 
    # @param opts [Hash] the optional parameters
    # @return [Array<(AccountConfigResponse, Integer, Hash)>] AccountConfigResponse data, response status code and response headers
    def confluent_cloud_public3_with_http_info(body, opts = {})

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ConfluentCloudAccountsAPIAPI.confluent_cloud_public3 ...'
      end
      # verify the required parameter 'body' is set
      if @api_client.config.client_side_validation && body.nil?
        fail ArgumentError, "Missing the required parameter 'body' when calling ConfluentCloudAccountsAPIAPI.confluent_cloud_public3"
      end
      # resource path
      local_var_path = '/api/v2/integrations/confluent-cloud/accounts'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(body)

      # return_type
      return_type = opts[:debug_return_type] || 'AccountConfigResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth]

      new_options = opts.merge(
        :operation => :confluent_cloud_public3,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Post, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ConfluentCloudAccountsAPIAPI#confluent_cloud_public3\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Update Confluent account.
    #
    # @see #confluent_cloud_public4_with_http_info
    def confluent_cloud_public4(account_id, body, opts = {})
      data, _status_code, _headers = confluent_cloud_public4_with_http_info(account_id, body, opts)
      data
    end

    # Update Confluent account.
    #
    # Update the Confluent account with the provided account ID.
    #
    # @param account_id [String] None
    # @param body [UpdateAccountRequest] 
    # @param opts [Hash] the optional parameters
    # @return [Array<(AccountConfigResponse, Integer, Hash)>] AccountConfigResponse data, response status code and response headers
    def confluent_cloud_public4_with_http_info(account_id, body, opts = {})

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ConfluentCloudAccountsAPIAPI.confluent_cloud_public4 ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling ConfluentCloudAccountsAPIAPI.confluent_cloud_public4"
      end
      # verify the required parameter 'body' is set
      if @api_client.config.client_side_validation && body.nil?
        fail ArgumentError, "Missing the required parameter 'body' when calling ConfluentCloudAccountsAPIAPI.confluent_cloud_public4"
      end
      # resource path
      local_var_path = '/api/v2/integrations/confluent-cloud/accounts/{account_id}'.sub('{account_id}', CGI.escape(account_id.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(body)

      # return_type
      return_type = opts[:debug_return_type] || 'AccountConfigResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth]

      new_options = opts.merge(
        :operation => :confluent_cloud_public4,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Patch, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ConfluentCloudAccountsAPIAPI#confluent_cloud_public4\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Delete Confluent account.
    #
    # @see #confluent_cloud_public5_with_http_info
    def confluent_cloud_public5(account_id, opts = {})
      confluent_cloud_public5_with_http_info(account_id, opts)
      nil
    end

    # Delete Confluent account.
    #
    # Delete a Confluent account with the provided account ID.
    #
    # @param account_id [String] None
    # @param opts [Hash] the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def confluent_cloud_public5_with_http_info(account_id, opts = {})

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ConfluentCloudAccountsAPIAPI.confluent_cloud_public5 ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling ConfluentCloudAccountsAPIAPI.confluent_cloud_public5"
      end
      # resource path
      local_var_path = '/api/v2/integrations/confluent-cloud/accounts/{account_id}'.sub('{account_id}', CGI.escape(account_id.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth]

      new_options = opts.merge(
        :operation => :confluent_cloud_public5,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Delete, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ConfluentCloudAccountsAPIAPI#confluent_cloud_public5\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List Confluent Account resources.
    #
    # @see #confluent_cloud_public6_with_http_info
    def confluent_cloud_public6(account_id, opts = {})
      data, _status_code, _headers = confluent_cloud_public6_with_http_info(account_id, opts)
      data
    end

    # List Confluent Account resources.
    #
    # Get a Confluent resource for the account associated with the provided ID.
    #
    # @param account_id [String] None
    # @param opts [Hash] the optional parameters
    # @return [Array<(AccountConfigResponse, Integer, Hash)>] AccountConfigResponse data, response status code and response headers
    def confluent_cloud_public6_with_http_info(account_id, opts = {})

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ConfluentCloudAccountsAPIAPI.confluent_cloud_public6 ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling ConfluentCloudAccountsAPIAPI.confluent_cloud_public6"
      end
      # resource path
      local_var_path = '/api/v2/integrations/confluent-cloud/accounts/{account_id}/resources'.sub('{account_id}', CGI.escape(account_id.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'AccountConfigResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth]

      new_options = opts.merge(
        :operation => :confluent_cloud_public6,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Get, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ConfluentCloudAccountsAPIAPI#confluent_cloud_public6\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get resource from Confluent account.
    #
    # @see #confluent_cloud_public7_with_http_info
    def confluent_cloud_public7(account_id, resource_id, opts = {})
      data, _status_code, _headers = confluent_cloud_public7_with_http_info(account_id, resource_id, opts)
      data
    end

    # Get resource from Confluent account.
    #
    # Get a Confluent resource with the provided resource id for the account associated with the provided account ID.
    #
    # @param account_id [String] None
    # @param resource_id [String] None
    # @param opts [Hash] the optional parameters
    # @return [Array<(ConfluentCloudResourcesResponse, Integer, Hash)>] ConfluentCloudResourcesResponse data, response status code and response headers
    def confluent_cloud_public7_with_http_info(account_id, resource_id, opts = {})

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ConfluentCloudAccountsAPIAPI.confluent_cloud_public7 ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling ConfluentCloudAccountsAPIAPI.confluent_cloud_public7"
      end
      # verify the required parameter 'resource_id' is set
      if @api_client.config.client_side_validation && resource_id.nil?
        fail ArgumentError, "Missing the required parameter 'resource_id' when calling ConfluentCloudAccountsAPIAPI.confluent_cloud_public7"
      end
      # resource path
      local_var_path = '/api/v2/integrations/confluent-cloud/accounts/{account_id}/resources/{resource_id}'.sub('{account_id}', CGI.escape(account_id.to_s).gsub('%2F', '/')).sub('{resource_id}', CGI.escape(resource_id.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'ConfluentCloudResourcesResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth]

      new_options = opts.merge(
        :operation => :confluent_cloud_public7,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Get, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ConfluentCloudAccountsAPIAPI#confluent_cloud_public7\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Add resource to Confluent account.
    #
    # @see #confluent_cloud_public8_with_http_info
    def confluent_cloud_public8(account_id, body, opts = {})
      data, _status_code, _headers = confluent_cloud_public8_with_http_info(account_id, body, opts)
      data
    end

    # Add resource to Confluent account.
    #
    # Create a Confluent resource for the account associated with the provided ID.
    #
    # @param account_id [String] None
    # @param body [ConfluentCloudResourceRequest] 
    # @param opts [Hash] the optional parameters
    # @return [Array<(ConfluentCloudResourceResponse, Integer, Hash)>] ConfluentCloudResourceResponse data, response status code and response headers
    def confluent_cloud_public8_with_http_info(account_id, body, opts = {})

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ConfluentCloudAccountsAPIAPI.confluent_cloud_public8 ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling ConfluentCloudAccountsAPIAPI.confluent_cloud_public8"
      end
      # verify the required parameter 'body' is set
      if @api_client.config.client_side_validation && body.nil?
        fail ArgumentError, "Missing the required parameter 'body' when calling ConfluentCloudAccountsAPIAPI.confluent_cloud_public8"
      end
      # resource path
      local_var_path = '/api/v2/integrations/confluent-cloud/accounts/{account_id}/resources'.sub('{account_id}', CGI.escape(account_id.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(body)

      # return_type
      return_type = opts[:debug_return_type] || 'ConfluentCloudResourceResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth]

      new_options = opts.merge(
        :operation => :confluent_cloud_public8,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Post, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ConfluentCloudAccountsAPIAPI#confluent_cloud_public8\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Update resource in Confluent account.
    #
    # @see #confluent_cloud_public9_with_http_info
    def confluent_cloud_public9(account_id, resource_id, body, opts = {})
      data, _status_code, _headers = confluent_cloud_public9_with_http_info(account_id, resource_id, body, opts)
      data
    end

    # Update resource in Confluent account.
    #
    # Update a Confluent resource with the provided resource id for the account associated with the provided account ID.
    #
    # @param account_id [String] None
    # @param resource_id [String] None
    # @param body [UpdateResourceRequest] 
    # @param opts [Hash] the optional parameters
    # @return [Array<(ConfluentCloudResourceResponse, Integer, Hash)>] ConfluentCloudResourceResponse data, response status code and response headers
    def confluent_cloud_public9_with_http_info(account_id, resource_id, body, opts = {})

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ConfluentCloudAccountsAPIAPI.confluent_cloud_public9 ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling ConfluentCloudAccountsAPIAPI.confluent_cloud_public9"
      end
      # verify the required parameter 'resource_id' is set
      if @api_client.config.client_side_validation && resource_id.nil?
        fail ArgumentError, "Missing the required parameter 'resource_id' when calling ConfluentCloudAccountsAPIAPI.confluent_cloud_public9"
      end
      # verify the required parameter 'body' is set
      if @api_client.config.client_side_validation && body.nil?
        fail ArgumentError, "Missing the required parameter 'body' when calling ConfluentCloudAccountsAPIAPI.confluent_cloud_public9"
      end
      # resource path
      local_var_path = '/api/v2/integrations/confluent-cloud/accounts/{account_id}/resources/{resource_id}'.sub('{account_id}', CGI.escape(account_id.to_s).gsub('%2F', '/')).sub('{resource_id}', CGI.escape(resource_id.to_s).gsub('%2F', '/'))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(body)

      # return_type
      return_type = opts[:debug_return_type] || 'ConfluentCloudResourceResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || [:apiKeyAuth, :appKeyAuth]

      new_options = opts.merge(
        :operation => :confluent_cloud_public9,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type,
        :api_version => "V2"
      )

      data, status_code, headers = @api_client.call_api(Net::HTTP::Patch, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ConfluentCloudAccountsAPIAPI#confluent_cloud_public9\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
